# Generated by Django 4.0.6 on 2022-09-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('blog_desc', models.TextField()),
                ('blog_img', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
