# Generated by Django 4.0.6 on 2022-09-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_category_cat_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='cat',
        ),
    ]
