# Generated by Django 4.0.6 on 2022-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_category_blog_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cat_num',
            field=models.IntegerField(default=0),
        ),
    ]
