# Generated by Django 4.0.6 on 2022-09-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_id',
            field=models.IntegerField(default=0),
        ),
    ]
