# Generated by Django 4.0.6 on 2022-10-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_blog_id_alter_blog_blog_id_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
