# Generated by Django 4.0.6 on 2022-10-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_profile_profile_image_profile_blog_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='blog_img',
            new_name='profile_img',
        ),
    ]
