# Generated by Django 4.0.6 on 2022-10-21 13:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0024_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='ContactUS',
        ),
    ]
