# Generated by Django 4.0.6 on 2022-10-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_contactus_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
