# Generated by Django 4.0.6 on 2022-10-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_pofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pofile',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
